# Generated by Django 3.1.1 on 2020-09-19 19:19

from django.db import migrations, models
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                ("brand", models.CharField(max_length=250, verbose_name="Brand")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price")),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="Send an image 500x500 pixels or in a proportional size",
                        upload_to="favorites/product",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "review_score",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=10, verbose_name="Review Score"
                    ),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Product", "ordering": ("title",),},
        ),
    ]
