# Generated by Django 3.1.1 on 2020-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this customer belongs to. A customer will get all permissions granted to each of their groups.",
                related_name="customers",
                related_query_name="customer",
                to="auth.Group",
                verbose_name="grupos",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only active customers can access the system.", verbose_name="Ativo?"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Determines whether the customer has access to the system panel.",
                verbose_name="Faz parte da equipe?",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                help_text="Enter the customer's full name.", max_length=200, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this customer.",
                related_name="customers",
                related_query_name="customer",
                to="auth.Permission",
                verbose_name="customer permissions",
            ),
        ),
    ]
