# Generated by Django 3.1.1 on 2020-09-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customers", "0002_auto_20200919_1217"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer", options={"verbose_name": "Usuário", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Os grupos aos quais este cliente pertence. Um cliente obterá todas as permissões concedidas acada um de seus grupos.",
                related_name="customers",
                related_query_name="customer",
                to="auth.Group",
                verbose_name="grupos",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Apenas clientes ativos podem acessar o sistema.",
                verbose_name="Ativo?",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Determina se o cliente tem acesso ao painel do sistema.",
                verbose_name="Faz parte da equipe?",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                help_text="Digite o nome completo do cliente.", max_length=200, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissões específicas para este cliente.",
                related_name="customers",
                related_query_name="customer",
                to="auth.Permission",
                verbose_name="permissões do cliente",
            ),
        ),
    ]
